version: '3.8'

services:
  # CRM应用服务 - 生产环境优化版
  crm-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: false
    image: crm-app:production
    container_name: crm-production
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///instance/edu_crm.db
      - SECRET_KEY=${SECRET_KEY:-crm-production-secret-$(date +%s)}
      # 生产环境优化配置
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=120
    volumes:
      # 使用绑定挂载，但会在初始化时从镜像复制数据库文件
      - ./instance:/app/instance
      # 日志文件持久化（设置正确权限）
      - ./logs:/app/logs:rw
      # 如果有静态文件需要持久化
      - ./static:/app/static:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health", "||", "curl", "-f", "http://localhost:80/auth/login"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    networks:
      - crm-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

networks:
  crm-network:
    driver: bridge
    name: crm-production-network
