services:
  crm-app:
    build: .
    container_name: crm-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=edu-crm-secret-key-2024
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
