version: '3.8'

services:
  # CRM应用服务 - 生产环境优化配置
  crm-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: crm-app:production
    container_name: crm-production
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      # 应用环境配置
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///instance/edu_crm.db
      - SECRET_KEY=${SECRET_KEY:-crm-production-secret-key-2024}
      - LOG_LEVEL=INFO
      
      # Python环境配置
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      
      # Gunicorn配置
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=120
      
    volumes:
      # 数据库文件持久化
      - crm_data:/app/instance
      # 日志文件持久化
      - crm_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/auth/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - crm-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# 数据卷
volumes:
  crm_data:
    driver: local
  crm_logs:
    driver: local

# 网络
networks:
  crm-network:
    driver: bridge
